### ISSUE TITLE
Linker error building on macos intel

### ISSUE THREAD

**Issue by tbillington** [tangramdotdev/tangram#104]
Hi, I got a build error while attempting to build tangram from macos.

Running `cargo build` from the root dir

The output is very large so I haven't included it, but these looked like the important parts:

```
 = note: Undefined symbols for architecture x86_64:
            "_PyList_Append", referenced from:
...
error: could not compile `tangram_python` due to previous error
```

**Comment by nitsky** [comment]
Hi @tbillington thank you for reporting this issue. I pushed a fix so this issue should now be resolved on the main branch. Please let me know if you still run into the problem, or close the issue if you observe it is resolved. Thank you! :)

**Comment by tbillington** [comment]
`cargo build` on master worked for my setup now !
