### ISSUE TITLE
Support for Deno and native ES modules

### ISSUE THREAD

**Issue by nitsky** [tangramdotdev/tangram#18]
The JavaScript library currently has support for Node.js and bundlers. We should be able to add support for Deno and native ES modules like so:

```js
import * as tangram from "https://js.tangram.xyz";
```

**Comment by yesmar** [comment]
I'd really like to be able to `import tangram from "@tangramdotdev/tangram";` in an ES6 module. Hopefully this feature will happen.

**Comment by isabella** [comment]
As of v0.7.0 you can `import * as tangram from "@tangramdotdev/tangram";` in an ES Module with Node.js v14 or later, so long as you set `"type": "module"` in your `package.json`. In the browser, you can `import * as tangram from "https://js.tangram.xyz";`, and in demo you `import * as tangram from "https://js.tangram.xyz/deno";`.

@yesmar does this satisfy what you are looking for?

**Comment by yesmar** [comment]
Yes, that totally works. I must have missed it in the docs. Thanks!

**Comment by nitsky** [comment]
@yesmar the docs use `require` for maximum compatibility, but the examples in the repo use es modules because they have their own `package.json`s so they can specify the `type` key.
