### ISSUE TITLE
Support yaml for configuration file

### ISSUE THREAD

**Issue by nitsky** [tangramdotdev/tangram#23]
As requested by @DannyBen, this issue tracks adding support for YAML as well as JSON for training configuration.

**Comment by nitsky** [comment]
@DannyBen this has been implemented in [this commit](https://github.com/tangramdotdev/tangram/commit/5b753a965d1bc0954ba0c5287c08601175b7fa83). It will be part of the next release.

**Comment by DannyBen** [comment]
Super nice! Thanks for the speedy implementation and for being open to it in the first place.
