### ISSUE TITLE
Email address?

### ISSUE THREAD

**Issue by jakelowen** [tangramdotdev/tangram#30]
HI - I attempted to email the address listed on the pricing page today and got the following bounce. Is there a better email to contact for pricing inquiries?

![image](https://user-images.githubusercontent.com/5368008/130307890-33324dab-7b74-4fe1-807b-ffca13a6b7ac.png)

**Comment by isabella** [comment]
Hey @jakelowen thank you for letting us know about this issue. We just switched to Google for mail and did not configure the hello@tangram.dev email address correctly. I just fixed it, please send your message again.
