### ISSUE TITLE
Train without header

### ISSUE THREAD

**Issue by Larsk97** [tangramdotdev/tangram#31]
Is it possible to train without having a header row, but rather specify column number somehow?

**Comment by nitsky** [comment]
Hi @Larsk97 at the moment a header is required. Can you just add a header with numbers in it? For example, if you have 4 columns, add the line "1,2,3,4" to the top of your CSV.

**Comment by Larsk97** [comment]
@nitsky That is what I did for now :+1: Thanks for reply!
