### ISSUE TITLE
Allow for use of sensible defaults when empty value is present

### ISSUE THREAD

**Issue by nicholasrobertm** [tangramdotdev/tangram#32]
When running my first test model I ran into the issue where my target field was sometimes empty (signifying zero, or 'no data' for that timeframe). It was a numeric field so It'd be nice to be able to set a value in my config.json that it defaults to when there is no data per field.

An additional side note but the lack of a --verbose flag to tell me which row it was failing on made it take longer to find what the actual problem was. The error it returned was "error: The target column contains invalid values." which was a bit vague till I realized it meant the target I was setting via the CLI.

**Comment by isabella** [comment]
Hi @nicholasrobertm thanks for opening this issue. I agree, that error message is awful, we will improve it to specify the row. In addition to including a "default target value" option in the config like you described, what do you think about tangram automatically dropping rows with empty values when the "default target value" option is not provided.

**Comment by nicholasrobertm** [comment]
Hey Isabella,

Thanks for getting back so quick, I think that makes sense! It would be useful to have a page / view to view dropped entries in, or at the very least a comma separated list of the row/line numbers outputted would work as well!

**Comment by nitsky** [comment]
I am thinking of adding a warning to the output on the command line indicating which rows are dropped.

If you are interested in contributing, this is a great first issue to tackle. Otherwise, I'll update this when we implement it.

**Comment by deciduously** [comment]
#63 closes
