### ISSUE TITLE
Ignoring CSV columns in input file

### ISSUE THREAD

**Issue by matthewrobertbell** [tangramdotdev/tangram#35]
(Great project by the way!)

It seems like it isn't currently possible to ignore CSV columns in the input file, this would be useful for training without having to process CSV files with things like database ID columns before starting training.

**Comment by nitsky** [comment]
Hi @matthewrobertbell, we don't currently have this option, so I will leave this issue open until we implement it. In the meantime, I suggest you try [xsv](https://github.com/BurntSushi/xsv). You can use it to create a new csv with a subset of the columns like so: `cat data.csv | xsv select column_a,column_b > data2.csv`.

**Comment by nitsky** [comment]
This is supported by specifying a subset of the columns with the `columns` key in a configuration file: https://www.tangram.dev/docs/guides/train_with_custom_configuration.
