### ISSUE TITLE
More informative CLI train output

### ISSUE THREAD

**Issue by otsaw** [tangramdotdev/tangram#44]
Currently when training a model, the output I get is

```
Computing features. 0ms
Training model 2 of 8. 0s 116ms
Computing model comparison features. 0ms
Computing comparison metric. 0ms
```

I'd prefer to see what kind of model it's training and what the value of the comparison metric is. So, something similar to in the app's "All Models" table under "Grid", but save me a bit of time not having to go there. For example

```
Computing features. 0ms
Training model 2 of 8: Linear. 0s 116ms
Computing model comparison features. 0ms
Computing comparison metric: AUC 0.765832. 0ms
...
Finalizing the best model: Linear AUC 0.765832. 0ms
```

I also noticed that I can guess the final model type based on filesize, but it would be nice if it was clearly in the output.

**Comment by isabella** [comment]
Hi otsaw! You are right we definitely should add this information to the CLI. I'll keep this issue open until we implement this.

**Comment by deciduously** [comment]
#61 closes
