### ISSUE TITLE
Check mark shows up as tofu

### ISSUE THREAD

**Issue by otsaw** [tangramdotdev/tangram#45]
This is not a big deal, but in the CLI training output, the check mark you're using shows up as tofu for me. I'm using the Cascadia Code font, which doesn't include that character. Maybe you could switch to the regular check mark Unicode 2713? That's in Cascadia Code and probably more common elsewhere too. (For what it's worth, I don't really like to see fancy characters in CLI output at all, but that seems to be a lost battle as it's more and more common.)

**Comment by nitsky** [comment]
Hey, I use a font that also does not include all emoji, and I was able to resolve my issue by adding an emoji specific font such as Noto Fonts Emoji. I sympathize with your desire for simple CLI output, but I agree it is a lost battle. We would prefer not to support a flag to disable emoji specifically, but you can turn off the fancy CLI output with `--no-progress`.
