### ISSUE TITLE
Allow fixing a single parameter value

### ISSUE THREAD

**Issue by otsaw** [tangramdotdev/tangram#46]
I have two potential use cases where I'd like to fix a single parameter value, but otherwise get the full default parameter grid. If I understand correctly, currently I'd have to specify that full grid in quite verbose JSON, which is a bit much.

1. For the data I have (lots of dummy variables), both linear and GBDT models do well and, perhaps depending on the downsampling stochastics, sometimes I get a linear model as best, sometimes GBDT. I'd like to fix that so that only linear models are tried (or only GBDT), because I don't want a discontinuity in production of having now a linear model, a month later GBDT, then linear again, etc.
2. If I oversample (which I'm not currently doing), I believe I need to fix the `min_examples_per_node` to more than the upsampling replication count. I'd like to set that but otherwise get the default grid.

If you want to keep the CLI simple, having these via Python (#12) would be fine for me too.

**Comment by isabella** [comment]
You can absolutely pass a config file that contains only a subset of the information! For instance, the following config file will result in only a single tree model getting trained with only the `min_examples_per_node` parameter overridden:
```
{
  "train": {
    "grid": [
      {
        "model": "tree",
        "min_examples_per_node": 100
      }
    ]
  }
}
```
All of the parameters that you do not specify will be filled with their default parameter values.

For linear models:
```
l2_regularization: 0.0
learning_rate: 0.1
max_epochs: 100
n_examples_per_batch: 32
```

For tree models:
```
binned_features_layout: BinnedFeaturesLayout::ColumnMajor
compute_losses: false
early_stopping_options: None
l2_regularization_for_continuous_splits: 0.0
l2_regularization_for_discrete_splits: 10.0
learning_rate: 0.1
max_depth: None
max_leaf_nodes: 31
max_rounds: 100
max_valid_bins_for_number_features: 255
min_examples_per_node: 20
min_gain_to_split: 0.0
min_sum_hessians_per_node: 1e-3
max_examples_for_computing_bin_thresholds: 200_000
smoothing_factor_for_discrete_bin_sorting: 10.0
```

The only detail which is a little unexpected here is that if you do not explicitly specify early stopping options in the config, early stopping will be disabled. We are considering changing this behavior to enable early stopping by default. If you would like to see an example of how to configure early stopping, see: https://github.com/tangramdotdev/tangram/issues/36.

**Comment by otsaw** [comment]
> All of the parameters that you do not specify will be filled with their default parameter values.

Instead of the default _value_, I'd like to get the default _grid search_ for those, so that the unspecified parameters would be optimized.

**Comment by nitsky** [comment]
Hey @otsaw, we have been thinking of adding an "autogrid" config option that will allow you to customize the default hyperparameter grid. For example, to restrict the default grid to linear models, you would be able to do something like this:

```json
{
  "train": {
    "autogrid": {
      "model_types": ["linear"]
    }
  }
}
```

How does that sound?

**Comment by otsaw** [comment]
That sounds good :+1:

**Comment by deciduously** [comment]
#66 closes
