### ISSUE TITLE
predict CLI should support --threshold

### ISSUE THREAD

**Issue by comunidadio** [tangramdotdev/tangram#62]
Threshold option is available from libraries (or predict server) but not available from the CLI - ideally it should be available too.

**Comment by nitsky** [comment]
Great idea, we'll implement this shortly.

**Comment by deciduously** [comment]
Good suggestion @comunidadio - [latest commit](https://github.com/tangramdotdev/tangram/commit/c11fbda2af245f99f01744eb64a81354b0a53c6b) adds this flag.
