### ISSUE TITLE
Default values when specifying only model type in config.json?

### ISSUE THREAD

**Issue by comunidadio** [tangramdotdev/tangram#65]
I was trying to limit tangram to just use linear models, using config.json, to save time while iterating on train data and found out unsurprising results (great).

Then I tried to run just "tree" model, and I'm surprised by both the AUC (slightly "better" than the regular 4 tree models tested) and the run time especially (much shorter)

```
ubuntu@ip-172-31-30-245:~$ cat config.json 
{
	"train": {
		"grid": [
			{
				"model": "tree"
			}
		]
	}
}
ubuntu@ip-172-31-30-245:~$ time tangram train --file flight_delays_train.csv --target dep_delayed_15min --output flight_delays.tangram -c config.json 
✅ Inferring train table columns. 0s 34ms
✅ Loading train table. 0s 29ms
✅ Shuffling. 0s 8ms
✅ Computing train stats. 0s 45ms
✅ Computing test stats. 0s 12ms
✅ Finalizing stats. 0ms
✅ Computing baseline metrics. 0ms
info: Press ctrl-c to stop early and save the best model trained so far.
✅ Computing features. 0s 98ms
✅ Preparing model 1 of 1: Tree. 0s 47ms
✅ Training model 1 of 1. 3s
✅ Computing model comparison features. 0s 66ms
️️️️✅ Computing comparison metric. 0s 50ms
info: 🎯 Model 1 AUC ROC: 0.734537
✅ Computing test features. 0s 129ms
✅ Testing. 0s 103ms
✅ Finalizing the best model. 0ms
info: Selected Tree Model 1 of 1 for binary classification result (AUC ROC: 0.734537)
Your model was written to flight_delays.tangram.
For help making predictions in your code, read the docs at https://www.tangram.dev/docs.
To learn more about how your model works and set up production monitoring, run `tangram app`.

real	0m4.042s
user	0m13.177s
sys	0m0.359s
```

Original run with all models take much longer than 4 seconds for each Tree model tentative:

```
ubuntu@ip-172-31-30-245:~$ time tangram train --file flight_delays_train.csv --target dep_delayed_15min --output flight_delays.tangram 
(...)
info: Selected Tree Model 8 of 8 for binary classification result (AUC ROC: 0.7289399)
Your model was written to flight_delays.tangram.
For help making predictions in your code, read the docs at https://www.tangram.dev/docs.
To learn more about how your model works and set up production monitoring, run `tangram app`.

real	1m0.856s
user	3m12.672s
sys	0m17.069s
```

1) are the default parameters correctly set if just selecting model name in config.json? are they documented somewhere?
2) would it make sense to have shorthand options --linear or --tree to allow quick evaluation of training data with a grid of 4 each?

**Comment by deciduously** [comment]
I @comunidadio - see #66.  The new `autogrid` config option will produce this behavior, if you specify `"model_types": ["linear"]` in your `train` options Tangram will train 4 linear models.

The default parameters are indeed set if you specify the model type.  You can inspect the default values at https://github.com/tangramdotdev/tangram/blob/c23a43ca17897275e1d543970cff2511f2d977c4/crates/core/grid.rs#L309
