### ISSUE TITLE
Expose training via HTTP

### ISSUE THREAD

**Issue by comunidadio** [tangramdotdev/tangram#67]
Perhaps using /training/... path from recently added "serve" command.

This would allow interact with training from any programming language, including from browser.
Perhaps could even be used by most libraries for #12 (especially the languages who do not have nice bindings support)

**Comment by deciduously** [comment]
Hi @comunidadio, thank you for the suggestion but we don't currently plan to support this use case.  Is there another language you would like to see supported?

**Comment by comunidadio** [comment]
I'm using both Go and Python for a project. Was thinking this could be a nice way to sidestep #12 for all languages in one go, but I can do with process spawning and stdout/err scraping for now indeed.

**Comment by nitsky** [comment]
We are actively working on #12. We will update you with progress soon!
