### ISSUE TITLE
Handling of +Inf/-Inf/NaN

### ISSUE THREAD

**Issue by comunidadio** [tangramdotdev/tangram#68]
Currently if a feature contains+Inf,-Inf,NaN as a value, the whole column is "silently" considered as Text.

Could Tangram handle those gracefully?
If have to special case those, would it be treated as missing value (possible for both Tree and Linear models?) or should it warn and ignore the impacted row/sample?

**Comment by comunidadio** [comment]
Sorry just to clarify the fix, "invalid" value means that specific feature is ignored or the whole row/sample?

If the former, does that work well with both linear and tree model? afaik trees are more tolerant to missing values than linear?

**Comment by nitsky** [comment]
For linear models, invalid values are replaced with the mean for the feature. Tree models are able to handle invalid values separately from valid values, so they do not need to be replaced.

**Comment by cedricjirnexu** [comment]
Thanks for the clarification.
