### ISSUE TITLE
Selection of "positive" label?

### ISSUE THREAD

**Issue by comunidadio** [tangramdotdev/tangram#69]
In binary classification, how does Tangram picks which label is considered as "positive" in tangram app reports (eg. Training Metrics) and for thresholding?  any way to force the "positive" label according to the use case?

**Comment by nitsky** [comment]
The negative label is the first label and the positive label is the second. By default, the labels are sorted alphabetically. This works well for common values like false/true, no/yes, and negative/positive. You can use a configuration file to customize the order of the enum options. See the docs here: https://www.tangram.dev/docs/guides/train_with_custom_configuration. Let me know if you still need help!
