### ISSUE TITLE
How to fix imbalanced dataset in tangram

### ISSUE THREAD

**Issue by iamharikrishnank** [tangramdotdev/tangram#72]
Our dataset is imbalanced.Some values are greater in number compared to majority values in dataset. How can it be solved while creating model in tangram using custom configuration

**Comment by isabella** [comment]
Hi @iamharikrishnank:  Currently, Tangram does not automatically handle imbalanced datasets. It is something that we are actively working on, here is the issue to track it: https://github.com/tangramdotdev/tangram/issues/39#issue-992353507.  Here is a discussion where we talk about the best ways to handle this for now: https://github.com/tangramdotdev/tangram/discussions/38. Let me know if you have more questions. Also, if you have a preference of how Tangram will automatically handle imbalanced datasets, let us know!

**Comment by nitsky** [comment]
I am going to close this as a duplicate of #39.
