### ISSUE TITLE
App identifier dosent match identifier in log_prediction

### ISSUE THREAD

**Issue by komatded** [tangramdotdev/tangram#87]
Good evening!

I recently tried to push model predictions into an application and discovered that identifiers I specified in `log_prediction` function did not match identifiers that appeared in the application. I use `python3.9` and `tangram==0.7.0`.

Here are screenshots:

> Python code

<img width="449" alt="Снимок экрана 2022-01-11 в 23 28 51" src="https://user-images.githubusercontent.com/69629500/149017200-a0c9585d-8ecc-4db0-84c7-348bc96a2ed4.png">

> Event in the app. Here it says that prediction identifier is the same as in python code, but actual identifier for this prediction is `3237cbe3097c87f5e73b7ce796f38be7`, as stated in the its link. And if I want to use log_true_value for this prediction, I have to use `3237cbe3097c87f5e73b7ce796f38be7` but not the original id

<img width="888" alt="Снимок экрана 2022-01-11 в 23 28 58" src="https://user-images.githubusercontent.com/69629500/149017219-9005395a-d101-4080-98ce-04ba6908e9fd.png">

**Comment by nitsky** [comment]
Hi @komatded, what you see in the URL for a prediction is what we call the prediction's `id`, which is unique and automatically generated. It is intentionally different from the `identifier` for that prediction. The `id` is always unique, but it's possible, though discouraged, for you to log multiple predictions with the same `identifier`. Does that make sense?

I just tried the example in `languages/python/examples/advanced` which logs a single prediction and true value to the app running locally, and was able to successfully associate the true value with the prediction using the `identifier`. Perhaps there is something different in your setup? Can you provide some more detailed steps to reproduce your problem? Thank you! :)

**Comment by komatded** [comment]
Hi @nitsky, thank you for your response!

I apologize for disturbing in vain :) Looks like I found what the problem was - in my train and test datasets target's column data type was `integer`, so I thought that I should also pass integer as `true_value` in `log_true_value`... now when I've passed it as a string everything worked fine!

Sorry, for bothering! I guess now this issue can be closed

**Comment by nitsky** [comment]
@komatded if the value is an integer you should not be required to pass it as a string. Is your model doing regression or classification?
