### ISSUE TITLE
Issue running cli from Docker

### ISSUE THREAD

**Issue by joelchen** [tangramdotdev/tangram#88]
When I tried to run tangram cli through Rust's Command from Docker container, there will be the following error:
```
error: No such device or address (os error 6)
```
Sample project: https://github.com/joelchen/train

**Comment by joelchen** [comment]
This works: `docker run -it train`
This does not work: `docker run train`
How do I make TTY not necessary for it to work?

**Comment by nitsky** [comment]
You can use the `--no-progress` flag.

**Comment by joelchen** [comment]
@nitsky Used `--no-progress` on the server and got the following:
```
errorerror: No such device or address (os error 6)
: No such device or address (os error 6)
error: Broken pipe (os error 32)
```
That is why I am trying to reproduce on local and fix it.

**Comment by joelchen** [comment]
Resorted to not using Command by copying chunks of tangram-cli into application, and set `progress: false` in TrainArgs to prevent tortoise::terminal::Terminal from running.

**Comment by nitsky** [comment]
Thanks for finding this issue, I am reopening to track a proper fix.

**Comment by nitsky** [comment]
@joelchen thanks again for spotting this issue, I just committed  818b3c9 which no longer errors if a tty is not found.
